#//|>-----------------------------------------------------------------------------------------------------------------<|
#//| Copyright (c) 08 Jul 2026. All rights are reserved by ASI
#//|>-----------------------------------------------------------------------------------------------------------------<|

#// IMPORT
from sphinx_doclang.commands import Command, cmd_self_name, cmd_self_type, cmd_self_obj


#// GLOBAL VARIABLES
TAB: str = " " * 4


@Command.overwrite("title")
def custom_title(context, *args, decorator="=", **kwargs):
    title = f"[ {context} ]"
    underline = decorator * len(title)
    return f"{title}\n{underline}"


#//|>-----------------------------------------------------------------------------------------------------------------<|
#//| DocLang Documentation Commands
#//|>-----------------------------------------------------------------------------------------------------------------<|
# noinspection PyUnusedLocal
@Command.new("show code")
def cmd_show_code(*args, language: str = "python", **kwargs) -> list[str]:
    """
    Displays a code example from the ``examples/docs`` directory.

    The positional arguments are joined to form the relative path to the file.
    The ``language`` option controls the syntax highlighting used in the output.

    Usage:
        - § show code : example.py ¶
        - § show code : folder, example.py, language = cpp ¶
        - § show code : path/to/example.py, language = cpp ¶
    """
    return [
        f".. literalinclude:: /../examples/docs/{"/".join(args)}",
        f"{TAB}:language: {language}",
        f"{TAB}:linenos:"
    ]


# noinspection PyUnusedLocal
@Command.new("show image")
def cmd_show_image(*args, align: str = "center", **kwargs) -> list[str]:
    """
    Displays an image from the ``examples/docs/preview`` directory.

    The positional arguments are joined to form the relative path to the image.
    The ``align`` option controls how the image is positioned in the output.

    Usage:
        - § show image : image.png ¶
        - § show image : folder, image.png, align = left ¶
        - § show image : path/to/image.png, align = right ¶
    """
    return [
        f".. image:: /../examples/docs/preview/{"/".join(args)}",
        f"{TAB}:align: {align}"
    ]


# noinspection PyUnusedLocal
@Command.new("parameters")
def cmd_parameters_list(*args, title: str = "Parameters", **kwargs) -> list[str]:
    """
    Creates a **Parameters** dropdown panel.

    Keyword arguments are interpreted as parameter–description pairs and displayed as a two‑column list.

    Usage:
        - § parameters ¶
        - § parameters : param_1 = Some description., param_2 = Another description. ¶
    """
    return [
        f".. dropdown:: {title}",
        f"{TAB}:class-container: dk-default-value",
        "",
        f"{TAB}.. list-table::"
        f"{TAB * 2}:header-rows: 0",
        "",
        f"{TAB * 2}* - Name",
        f"{TAB * 2}  - Description",
        *cmd_parameters_item(**kwargs)
    ]


# noinspection PyUnusedLocal
@Command.new("param")
def cmd_parameters_item(*args, **kwargs) -> list[str]:
    """
    Adds parameter entries to the list generated by the ``parameters`` command.

    Keyword arguments are interpreted as parameter–description pairs.

    Usage:
        - § parameters ¶
        - § param : param_A = Description for A., param_B = Description for B. ¶
    """
    return [f"{TAB * 2}* - {f"\n{TAB * 2}  - ".join(kw)}" for kw in kwargs.items()]
